// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7igpKikzyLD6chwLwP1eLnhiCDXGS2RM',
    appId: '1:131197483809:web:6e8ab7c8f14bce35839c60',
    messagingSenderId: '131197483809',
    projectId: 'lemon-one',
    authDomain: 'lemon-one.firebaseapp.com',
    storageBucket: 'lemon-one.appspot.com',
    measurementId: 'G-N046WTSYG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybHUJ2yq16cHcERDuJAV3mOQRyegdq9c',
    appId: '1:131197483809:android:1fa3d014b59683e5839c60',
    messagingSenderId: '131197483809',
    projectId: 'lemon-one',
    storageBucket: 'lemon-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaycWngmtvmHHTEEzXkM0VIQ6Yy8MRYNU',
    appId: '1:131197483809:ios:c1ee4aed3f9afa25839c60',
    messagingSenderId: '131197483809',
    projectId: 'lemon-one',
    storageBucket: 'lemon-one.appspot.com',
    iosClientId: '131197483809-vvsonieca11b07qkq03pl61gc07r2l9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
